# Generated by Django 5.0 on 2025-09-16 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watch_list',
            field=models.ManyToManyField(blank=True, related_name='watch_listed_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
