# Generated by Django 5.0 on 2025-09-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_watch_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='amount_left',
            field=models.PositiveIntegerField(default=0, help_text='Number of copies available for purchase'),
        ),
    ]
