# Generated by Django 5.0 on 2025-10-13 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_movie_amount_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='stars',
        ),
    ]
